// ============================================
// 交流会マッチング - サンプルデータ
// ============================================

const CATEGORIES = [
  "経営者",
  "エンジニア",
  "クリエイター",
  "マーケター",
  "飲食",
  "美容・健康",
  "士業・コンサル",
  "不動産・金融",
];

const MEMBERS = [
  {
    id: 1,
    name: "佐藤 健一",
    company: "サトウ商事株式会社",
    category: "経営者",
    avatar: "👨‍💼",
    tags: ["卸売", "地域貢献", "二代目"],
    bio: "食品卸を営んで15年。地元の飲食店さんを盛り上げる企画を一緒にやれる方を探しています。",
    interest: "飲食店経営者・マーケターの方と話してみたい",
    isNew: true,
    isPickup: false,
  },
  {
    id: 2,
    name: "田中 美咲",
    company: "Misaki Design",
    category: "クリエイター",
    avatar: "👩‍🎨",
    tags: ["ロゴ制作", "ブランディング", "フリーランス"],
    bio: "デザイン事務所を経営しています。ロゴやパンフレットなど、想いが伝わるデザインが得意です。",
    interest: "創業したての経営者さんの力になりたい",
    isNew: true,
    isPickup: true,
  },
  {
    id: 3,
    name: "鈴木 大輔",
    company: "株式会社テックフロンティア",
    category: "エンジニア",
    avatar: "👨‍💻",
    tags: ["Web開発", "DX支援", "AI活用"],
    bio: "業務システムやWebアプリの受託開発をしています。「ITで困っている」を気軽に相談してください。",
    interest: "DXに悩む中小企業の経営者さんと",
    isNew: true,
    isPickup: false,
  },
  {
    id: 4,
    name: "高橋 由紀",
    company: "カフェ・ソレイユ",
    category: "飲食",
    avatar: "👩‍🍳",
    tags: ["カフェ経営", "地産地消", "イベント好き"],
    bio: "駅前でカフェを経営して8年。店舗を使ったコラボイベントをいつでも歓迎しています!",
    interest: "イベントを一緒に企画できる方",
    isNew: true,
    isPickup: false,
  },
  {
    id: 5,
    name: "伊藤 誠",
    company: "伊藤会計事務所",
    category: "士業・コンサル",
    avatar: "🧑‍💼",
    tags: ["税理士", "創業支援", "資金繰り"],
    bio: "税理士として創業支援を中心に活動しています。お金の悩みは早めの相談が一番です。",
    interest: "創業3年以内の経営者さんを応援したい",
    isNew: false,
    isPickup: true,
  },
  {
    id: 6,
    name: "渡辺 沙織",
    company: "Salon SAORI",
    category: "美容・健康",
    avatar: "💇‍♀️",
    tags: ["美容室", "3店舗経営", "採用強化中"],
    bio: "美容室を3店舗経営しています。スタッフ採用と教育に力を入れており、人事の話が大好きです。",
    interest: "採用・組織づくりに詳しい方と",
    isNew: false,
    isPickup: false,
  },
  {
    id: 7,
    name: "山本 拓也",
    company: "ヤマモト不動産",
    category: "不動産・金融",
    avatar: "🏠",
    tags: ["賃貸仲介", "空き家活用", "リノベ"],
    bio: "地域の不動産屋の3代目です。空き家を活用した新しい事業アイデアを模索中です。",
    interest: "空き家活用のアイデアを持つ方",
    isNew: false,
    isPickup: false,
  },
  {
    id: 8,
    name: "中村 恵",
    company: "株式会社グロースリンク",
    category: "マーケター",
    avatar: "📈",
    tags: ["SNS運用", "広告運用", "分析好き"],
    bio: "中小企業のSNS・Web広告の運用代行をしています。「発信が続かない」を仕組みで解決します。",
    interest: "発信に悩む店舗オーナーさんと",
    isNew: false,
    isPickup: true,
  },
  {
    id: 9,
    name: "小林 亮",
    company: "リョウ・エンジニアリング",
    category: "エンジニア",
    avatar: "🔧",
    tags: ["IoT", "製造業", "ものづくり"],
    bio: "製造業向けのIoTシステムを開発しています。現場のカイゼンをテクノロジーで支えます。",
    interest: "製造業・工場を経営されている方",
    isNew: false,
    isPickup: false,
  },
  {
    id: 10,
    name: "加藤 真理子",
    company: "MARIKO english school",
    category: "経営者",
    avatar: "👩‍🏫",
    tags: ["英会話教室", "教育", "海外展開"],
    bio: "子ども向け英会話教室を運営しています。教育×地域で何か面白いことを仕掛けたいです。",
    interest: "教育に興味のある異業種の方",
    isNew: false,
    isPickup: false,
  },
  {
    id: 11,
    name: "吉田 隼人",
    company: "映像制作 HAYATO FILMS",
    category: "クリエイター",
    avatar: "🎬",
    tags: ["動画制作", "PR動画", "ドローン"],
    bio: "企業PR動画や採用動画を制作しています。ドローン撮影もお任せください。",
    interest: "動画で会社の魅力を伝えたい方",
    isNew: true,
    isPickup: false,
  },
  {
    id: 12,
    name: "松本 千夏",
    company: "ちなつ整骨院",
    category: "美容・健康",
    avatar: "💆‍♀️",
    tags: ["整骨院", "健康経営", "セミナー登壇"],
    bio: "整骨院を経営しつつ、企業向けに健康経営セミナーを行っています。従業員の健康づくりをサポートします。",
    interest: "従業員の健康に関心のある経営者さん",
    isNew: false,
    isPickup: false,
  },
  {
    id: 13,
    name: "井上 剛",
    company: "井上社会保険労務士事務所",
    category: "士業・コンサル",
    avatar: "📋",
    tags: ["社労士", "労務相談", "助成金"],
    bio: "社労士として労務管理・助成金申請をサポートしています。「人」の悩みはお気軽にどうぞ。",
    interest: "従業員を初めて雇う経営者さん",
    isNew: false,
    isPickup: false,
  },
  {
    id: 14,
    name: "木村 彩花",
    company: "Ayaka Marketing Lab",
    category: "マーケター",
    avatar: "💡",
    tags: ["ブランド戦略", "女性向け商材", "EC"],
    bio: "女性向け商材のブランド戦略とEC支援が専門です。数字とデザインの両面から伴走します。",
    interest: "ECに挑戦したい店舗オーナーさん",
    isNew: true,
    isPickup: false,
  },
  {
    id: 15,
    name: "林 正義",
    company: "居酒屋 まさよし",
    category: "飲食",
    avatar: "🍶",
    tags: ["居酒屋", "日本酒", "宴会歓迎"],
    bio: "地酒にこだわった居酒屋を営んでいます。交流会の二次会はぜひうちで!仕入れのつながりも探しています。",
    interest: "酒蔵・生産者さんとつながりたい",
    isNew: false,
    isPickup: false,
  },
  {
    id: 16,
    name: "斎藤 学",
    company: "サイトウファイナンシャル",
    category: "不動産・金融",
    avatar: "💹",
    tags: ["FP", "資産形成", "保険見直し"],
    bio: "ファイナンシャルプランナーとして経営者の資産形成をサポートしています。まずは雑談からどうぞ。",
    interest: "資産づくりに関心のある方",
    isNew: false,
    isPickup: false,
  },
];

// イベントデータ(day は開催日、month は 0 始まりでなく 1-12 表記)
const EVENTS = [
  { year: 2026, month: 7, day: 30, name: "第42回 定例交流会", place: "市民会館 大ホール 18:30〜" },
  { year: 2026, month: 8, day: 6, name: "朝活ビジネス交流会", place: "カフェ・ソレイユ 7:30〜" },
  { year: 2026, month: 8, day: 12, name: "業種別ランチ会(IT・クリエイター)", place: "駅前ダイニング 12:00〜" },
  { year: 2026, month: 8, day: 20, name: "第43回 定例交流会", place: "市民会館 大ホール 18:30〜" },
  { year: 2026, month: 8, day: 27, name: "ゴルフコンペ懇親会", place: "グリーンヒルCC 9:00〜" },
  { year: 2026, month: 9, day: 3, name: "新会員歓迎会", place: "居酒屋まさよし 19:00〜" },
  { year: 2026, month: 9, day: 17, name: "第44回 定例交流会", place: "市民会館 大ホール 18:30〜" },
];
