// ============================================
// 紹介先早見表 - データ
// 山本 捷真(Lumenium)以外の26名はサンプルです。
// 実際の会員情報に差し替えてご利用ください。
// ============================================

const COMMUNITY = {
  label: "BT-EX5 ／ 新潟・東京 紹介者制コミュニティ",
  realMemberNote: "山本以外の26名はサンプルです。実際の情報に差し替えてご利用ください。",
};

const REF_CATEGORIES = [
  "IT・Web・クリエイティブ",
  "士業・専門家",
  "お金・保険",
  "住まい・不動産",
  "人材・組織",
  "美容・健康",
  "食・地域産品",
  "暮らし・サービス",
];

// 紹介診断の質問で使う選択肢。id はメンバーの topics / targets / prospects と対応する
const TOPICS = [
  { id: "efficiency", label: "業務の効率化・システム化" },
  { id: "web", label: "ホームページ・集客・SNS" },
  { id: "ai", label: "AI活用・AI研修" },
  { id: "video", label: "動画・PR" },
  { id: "design", label: "デザイン・印刷物" },
  { id: "tax", label: "税金・会計" },
  { id: "legal", label: "契約・法律・許認可" },
  { id: "funding", label: "資金調達・補助金・融資" },
  { id: "insurance", label: "保険・資産・相続" },
  { id: "realestate", label: "不動産・物件・空き家" },
  { id: "reform", label: "リフォーム・内装" },
  { id: "hiring", label: "採用・人材" },
  { id: "org", label: "組織づくり・社員研修" },
  { id: "labor", label: "労務・助成金" },
  { id: "health", label: "健康・美容" },
  { id: "food", label: "食・ギフト・仕入れ" },
  { id: "event", label: "イベント・会場" },
  { id: "life", label: "暮らし(車・介護・家事)" },
];

const PROSPECTS = [
  { id: "owner", label: "経営者・個人事業主" },
  { id: "staff", label: "会社の担当者・管理職" },
  { id: "individual", label: "個人(家庭・暮らしのこと)" },
];

const INDUSTRIES = [
  { id: "restaurant", label: "飲食" },
  { id: "retail", label: "小売・EC" },
  { id: "salon", label: "美容・サロン" },
  { id: "pro", label: "士業・専門職" },
  { id: "build", label: "製造・建設" },
  { id: "it", label: "IT・サービス" },
  { id: "medical", label: "医療・介護" },
  { id: "personal", label: "個人・家庭" },
];

const AREAS = [
  { id: "niigata", label: "新潟" },
  { id: "tokyo", label: "東京・関東" },
  { id: "other", label: "その他の地域" },
];

const MEETINGS = [
  { id: "face", label: "対面で会いたい" },
  { id: "online", label: "オンラインでよい" },
  { id: "either", label: "どちらでもよい" },
];

const ONLINE_LABELS = { all: "全国対応", partial: "打合せのみ可", none: "対面のみ" };

// online: all=オンライン全国対応 / partial=打合せのみ可 / none=対面のみ
// targets に "any" を含む人は業種を問わず紹介を受けられる
const REF_MEMBERS = [
  {
    id: "yamamoto",
    name: "山本 捷真",
    company: "Lumenium(ルメニウム)代表",
    base: "東京",
    category: "IT・Web・クリエイティブ",
    sample: false,
    business:
      "業務効率化システムの開発(予約・在庫・契約書・営業リストなど/30万〜600万円)、ホームページ・LP制作、社員向け生成AI研修・AI導入支援(講師1回10万円〜)。動画・SNS運用・LINE構築も対応。",
    note: "相談・見積り無料、48時間以内に返信。最低発注額なし、1業務・研修1回から。",
    wants:
      "紙・Excel・電話で業務を回している中小企業や複数店舗の経営者(飲食・小売・サロン・士業事務所など)/AIを導入したいが何から始めるか決まっていない会社",
    triggers: ["手作業に時間がかかる", "予約・在庫管理がバラバラ", "HPを作ったきり", "社員にAIを使わせたい", "AI研修", "LINEで集客"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["efficiency", "web", "ai", "video", "design", "org"],
    targets: ["restaurant", "retail", "salon", "pro", "build", "it"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s01",
    name: "佐藤 健一",
    company: "佐藤税理士事務所",
    base: "新潟",
    category: "士業・専門家",
    sample: true,
    business: "法人・個人の税務顧問、創業融資サポート、事業承継の税務。",
    note: "初回相談無料。クラウド会計の導入支援もしています。",
    wants: "開業1〜3年目の経営者/事業承継を考え始めた二代目・三代目",
    triggers: ["確定申告が大変", "税理士を変えたい", "融資を受けたい", "事業承継"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["tax", "funding"],
    targets: ["any"],
    prospects: ["owner"],
  },
  {
    id: "s02",
    name: "中川 由紀",
    company: "なかがわ社労士事務所",
    base: "新潟",
    category: "士業・専門家",
    sample: true,
    business: "労務相談、就業規則の作成、社会保険の手続き、雇用系助成金の申請。",
    note: "従業員5名からの顧問契約に対応。",
    wants: "初めて人を雇う経営者/パート・アルバイトが多い店舗",
    triggers: ["人を雇いたい", "就業規則がない", "助成金を使いたい", "労務トラブル"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["labor", "hiring"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s03",
    name: "長谷川 亮",
    company: "長谷川総合法律事務所",
    base: "東京",
    category: "士業・専門家",
    sample: true,
    business: "企業法務、契約書のチェック・作成、債権回収、顧問弁護士。",
    note: "スポット相談30分から。",
    wants: "取引先との契約が増えてきた会社/未払いに困っている事業者",
    triggers: ["契約書を見てほしい", "代金が払われない", "顧問弁護士", "トラブル"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["legal"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s04",
    name: "森 早苗",
    company: "もり行政書士事務所",
    base: "新潟",
    category: "士業・専門家",
    sample: true,
    business: "飲食・建設・産廃などの許認可申請、補助金の申請サポート、法人設立。",
    note: "補助金は事業計画書の作成から伴走します。",
    wants: "これから開業・新規事業を始める方/補助金を使いたい経営者",
    triggers: ["許可が必要", "補助金を使いたい", "会社を作りたい", "飲食店を開きたい"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "partial",
    topics: ["legal", "funding"],
    targets: ["restaurant", "build", "retail"],
    prospects: ["owner"],
  },
  {
    id: "s05",
    name: "渡辺 誠",
    company: "渡辺FP事務所",
    base: "東京",
    category: "お金・保険",
    sample: true,
    business: "ファイナンシャルプランナー。資産形成、保険の見直し、相続・贈与の相談。",
    note: "商品を売らない相談専門。",
    wants: "経営者個人の資産づくりに関心がある方/相続を考え始めたご家族",
    triggers: ["保険を見直したい", "資産運用", "相続が心配", "老後のお金"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["insurance"],
    targets: ["any"],
    prospects: ["owner", "individual"],
  },
  {
    id: "s06",
    name: "阿部 千尋",
    company: "あべ資金調達サポート",
    base: "新潟",
    category: "お金・保険",
    sample: true,
    business: "地銀出身。融資の相談、事業計画書の作成、補助金・制度融資の活用支援。",
    note: "金融機関との面談同席も可能。",
    wants: "設備投資や店舗拡大を考えている経営者/資金繰りに不安がある会社",
    triggers: ["融資を受けたい", "資金繰り", "設備投資", "事業計画書"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["funding", "tax"],
    targets: ["any"],
    prospects: ["owner"],
  },
  {
    id: "s07",
    name: "高野 大輔",
    company: "たかの保険サービス",
    base: "新潟",
    category: "お金・保険",
    sample: true,
    business: "損害保険代理店。店舗・事務所の火災保険、賠償責任保険、社用車の保険。",
    note: "今の保険証券を見るだけの相談も歓迎。",
    wants: "店舗や工場を持つ事業者/社用車を使う会社",
    triggers: ["保険が高い", "店舗の火災保険", "賠償が心配", "社用車"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "partial",
    topics: ["insurance"],
    targets: ["restaurant", "retail", "build", "salon"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s08",
    name: "山田 拓也",
    company: "山田不動産",
    base: "新潟",
    category: "住まい・不動産",
    sample: true,
    business: "売買・賃貸の仲介、空き家の活用・売却、店舗・事務所物件の紹介。",
    note: "空き家の無料査定をしています。",
    wants: "実家の空き家に困っている方/新潟で出店・移転を考えている事業者",
    triggers: ["空き家がある", "実家を売りたい", "店舗物件を探している", "移転"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "partial",
    topics: ["realestate"],
    targets: ["any"],
    prospects: ["owner", "individual"],
  },
  {
    id: "s09",
    name: "斎藤 恵",
    company: "さいとう工務店",
    base: "新潟",
    category: "住まい・不動産",
    sample: true,
    business: "住宅リフォーム、店舗の内装工事、水回り・外壁の修繕。",
    note: "見積り無料。小さな修繕からお受けします。",
    wants: "店舗の改装を考えている方/古い家の手直しをしたいご家庭",
    triggers: ["リフォーム", "内装を変えたい", "雨漏り", "店舗改装"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "none",
    topics: ["reform", "realestate"],
    targets: ["restaurant", "retail", "salon", "personal"],
    prospects: ["owner", "individual"],
  },
  {
    id: "s10",
    name: "石井 健太",
    company: "アーバンリーシング",
    base: "東京",
    category: "住まい・不動産",
    sample: true,
    business: "東京23区の店舗・事務所テナント仲介、オフィス移転のサポート。",
    note: "居抜き物件の情報が豊富です。",
    wants: "東京に出店・事務所を構えたい地方の会社/手狭になったオフィス",
    triggers: ["東京に出店", "事務所を移転", "居抜き物件", "オフィスが狭い"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["realestate"],
    targets: ["restaurant", "retail", "salon", "it", "pro"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s11",
    name: "松本 彩",
    company: "キャリアリンク新潟",
    base: "新潟",
    category: "人材・組織",
    sample: true,
    business: "人材紹介。正社員・UIターン人材の採用支援、求人票の作成サポート。",
    note: "成功報酬型。採用できるまで費用はかかりません。",
    wants: "人手不足に悩む中小企業/新潟にUターンしたい人材を探している会社",
    triggers: ["人が採れない", "求人を出しても来ない", "Uターン採用", "人手不足"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["hiring"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s12",
    name: "井上 隼人",
    company: "組織開発ラボ",
    base: "東京",
    category: "人材・組織",
    sample: true,
    business: "管理職研修、評価制度づくり、1on1の導入支援。",
    note: "社員20〜200名規模の会社が中心。",
    wants: "社員が増えてきて組織の悩みが出てきた経営者/離職が続いている会社",
    triggers: ["離職が多い", "評価制度", "管理職が育たない", "社員研修"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["org", "hiring"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s13",
    name: "木村 舞",
    company: "採用広報スタジオ",
    base: "東京",
    category: "人材・組織",
    sample: true,
    business: "採用ページの制作、採用SNSの運用代行、社員インタビュー記事。",
    note: "求人媒体に頼らない採用を作ります。",
    wants: "若手の応募を増やしたい会社/採用に使える発信がない会社",
    triggers: ["若手が来ない", "採用ページ", "採用SNS", "会社の魅力が伝わらない"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["hiring", "web"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s14",
    name: "加藤 真理子",
    company: "サロン・ド・マリ",
    base: "新潟",
    category: "美容・健康",
    sample: true,
    business: "エステ・フェイシャル、ブライダルエステ、メンズ脱毛。",
    note: "法人向けの福利厚生プランもあります。",
    wants: "結婚式を控えた方/社員の福利厚生を考えている会社",
    triggers: ["結婚式", "肌の悩み", "福利厚生", "プレゼント"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "none",
    topics: ["health"],
    targets: ["personal", "any"],
    prospects: ["individual", "staff"],
  },
  {
    id: "s15",
    name: "吉田 剛",
    company: "よしだ整骨院",
    base: "新潟",
    category: "美容・健康",
    sample: true,
    business: "腰痛・肩こりの施術、企業向けの健康セミナー・出張施術。",
    note: "健康経営の取り組み相談もどうぞ。",
    wants: "デスクワークや立ち仕事が多い職場/健康経営を始めたい会社",
    triggers: ["腰痛", "肩こり", "健康経営", "社員が疲れている"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "partial",
    topics: ["health"],
    targets: ["any"],
    prospects: ["individual", "owner", "staff"],
  },
  {
    id: "s16",
    name: "林 奈央",
    company: "パーソナルジム LUCE",
    base: "東京",
    category: "美容・健康",
    sample: true,
    business: "パーソナルトレーニング、食事指導、法人向け福利厚生プラン。",
    note: "オンラインレッスンも可能。",
    wants: "運動不足の経営者・会社員/福利厚生を充実させたい会社",
    triggers: ["運動不足", "ダイエット", "体力が落ちた", "福利厚生"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["health"],
    targets: ["any"],
    prospects: ["individual", "owner", "staff"],
  },
  {
    id: "s17",
    name: "清水 健",
    company: "しみず農園",
    base: "新潟",
    category: "食・地域産品",
    sample: true,
    business: "コシヒカリ・野菜の直販、法人ギフト、飲食店への卸。",
    note: "少量・定期の配送に対応。",
    wants: "地元の食材を使いたい飲食店/取引先への贈り物を探している会社",
    triggers: ["お米を仕入れたい", "地元の食材", "お歳暮・お中元", "ギフト"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["food"],
    targets: ["restaurant", "retail", "any"],
    prospects: ["owner", "staff", "individual"],
  },
  {
    id: "s18",
    name: "池田 さやか",
    company: "池田酒造",
    base: "新潟",
    category: "食・地域産品",
    sample: true,
    business: "日本酒の製造・販売、法人の記念品・ノベルティ、イベント出店。",
    note: "オリジナルラベルの記念酒が作れます。",
    wants: "周年記念や贈り物を探している会社/地酒を扱いたい飲食店",
    triggers: ["記念品", "日本酒", "周年記念", "地酒を置きたい"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["food", "event"],
    targets: ["restaurant", "retail", "any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s19",
    name: "橋本 翔",
    company: "ケータリング HASHIMOTO",
    base: "東京",
    category: "食・地域産品",
    sample: true,
    business: "社内イベント・パーティー・展示会のケータリング、お弁当の手配。",
    note: "10名様から対応。",
    wants: "社内イベントや懇親会を企画している総務・人事の方",
    triggers: ["懇親会", "社内イベント", "ケータリング", "お弁当"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "partial",
    topics: ["food", "event"],
    targets: ["any"],
    prospects: ["staff", "owner"],
  },
  {
    id: "s20",
    name: "山口 修",
    company: "山口オートサービス",
    base: "新潟",
    category: "暮らし・サービス",
    sample: true,
    business: "車検・整備、社用車のリース、中古車の販売。",
    note: "代車無料・引き取り納車に対応。",
    wants: "社用車を何台も持つ会社/車の買い替えを考えているご家庭",
    triggers: ["車検", "社用車", "車を買い替えたい", "リース"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "none",
    topics: ["life"],
    targets: ["build", "any"],
    prospects: ["owner", "individual"],
  },
  {
    id: "s21",
    name: "岡田 恵美",
    company: "おかだ介護相談室",
    base: "新潟",
    category: "暮らし・サービス",
    sample: true,
    business: "介護保険の申請サポート、施設・在宅サービス探しの相談。",
    note: "ご家族だけの相談も歓迎です。",
    wants: "親の介護が始まりそうな方/介護と仕事の両立に悩む社員がいる会社",
    triggers: ["親の介護", "施設を探している", "介護保険", "介護離職"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["life", "labor"],
    targets: ["personal", "medical", "any"],
    prospects: ["individual", "staff"],
  },
  {
    id: "s22",
    name: "前田 涼",
    company: "前田印刷",
    base: "新潟",
    category: "IT・Web・クリエイティブ",
    sample: true,
    business: "名刺・チラシ・パンフレット・看板・ノベルティの制作と印刷。",
    note: "デザインからまとめてお任せできます。",
    wants: "開業準備中の方/イベントや販促物を急ぎで用意したい会社",
    triggers: ["名刺を作りたい", "チラシ", "看板", "ノベルティ"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["design"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s23",
    name: "小林 美帆",
    company: "こばやしデザイン室",
    base: "新潟",
    category: "IT・Web・クリエイティブ",
    sample: true,
    business: "ロゴ・ブランドデザイン、パッケージ、店舗のメニュー表。",
    note: "想いを聞くところから一緒に作ります。",
    wants: "お店や商品の見た目を整えたい方/リブランディングを考えている会社",
    triggers: ["ロゴがない", "パッケージ", "メニュー表", "ブランドを変えたい"],
    face: "新潟県内",
    faceAreas: ["niigata"],
    online: "all",
    topics: ["design", "web"],
    targets: ["restaurant", "retail", "salon"],
    prospects: ["owner"],
  },
  {
    id: "s24",
    name: "石田 航",
    company: "映像制作 KOH FILMS",
    base: "東京",
    category: "IT・Web・クリエイティブ",
    sample: true,
    business: "企業PR動画・採用動画・ドローン撮影・YouTubeの編集。",
    note: "撮影は全国出張可。",
    wants: "会社や商品の魅力を動画で伝えたい会社",
    triggers: ["動画を作りたい", "採用動画", "YouTube", "ドローン"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "all",
    topics: ["video", "hiring"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s25",
    name: "藤田 健二",
    company: "FUJITA HALL",
    base: "東京",
    category: "暮らし・サービス",
    sample: true,
    business: "会議室・セミナー会場・パーティー会場の貸し出しと運営サポート。",
    note: "10〜150名まで対応。",
    wants: "セミナーや交流会の会場を探している主催者",
    triggers: ["会場を探している", "セミナー", "パーティー", "交流会を開きたい"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "none",
    topics: ["event"],
    targets: ["any"],
    prospects: ["owner", "staff"],
  },
  {
    id: "s26",
    name: "小川 明美",
    company: "家事代行 ここちよ",
    base: "東京",
    category: "暮らし・サービス",
    sample: true,
    business: "家事代行、整理収納、オフィスの定期清掃。",
    note: "スポット1回から利用できます。",
    wants: "共働きで家事が回らないご家庭/オフィスの清掃を任せたい会社",
    triggers: ["家事が回らない", "片付けたい", "オフィス清掃", "引越し前の整理"],
    face: "関東(東京拠点)",
    faceAreas: ["tokyo"],
    online: "none",
    topics: ["life"],
    targets: ["personal", "any"],
    prospects: ["individual", "staff"],
  },
];
